define([
    "common-ui/widgets/Button",
    "common-ui/widgets/Calendar",
    "common-ui/widgets/Content",
    "common-ui/widgets/DataSet",
    "common-ui/widgets/DomainItem",
    "common-ui/widgets/DomainItemOverview",
    "common-ui/widgets/DomainSummary",
    "common-ui/widgets/FileUpload",
    "common-ui/widgets/Image",
    "common-ui/widgets/InfoTooltip",
    "common-ui/widgets/MeasureItem",
    "common-ui/widgets/SelectionList",
    "common-ui/widgets/Stars",
    "common-ui/widgets/SummaryBar",
    "common-ui/widgets/SummaryBarItem",
    "common-ui/widgets/NotificationItem",
    "common-ui/widgets/Notification",
    "common-ui/widgets/OverviewToggleBar",
    "common-ui/widgets/ProgressBar",
    "common-ui/widgets/TitleBar",
    "common-ui/widgets/ToggleBar",
    "common-ui/widgets/container/SelectionListContainer",
    "common-ui/widgets/container/ProgrammaticContainer",
    "common-ui/widgets/container/ToggleBarContainer",
    "common-ui/widgets/container/ChartListToggleBarContainer",
    "common-ui/widgets/container/SimpleContainer",
    "common-ui/widgets/charting/BubbleLineChart",
    "common-ui/widgets/charting/SparkBarChart",
    "common-ui/widgets/charting/ComparativeBoxPlot",
    "common-ui/widgets/charting/ComparativeBoxPlotLegend",
    "common-ui/widgets/charting/Slider",
    "common-ui/widgets/charting/TimeSlider",
    "common-ui/widgets/charting/Legend",
    "common-ui/widgets/charting/DonutChart",
    "common-ui/widgets/charting/GaugeChart",
    "common-ui/widgets/charting/D3AreaChart",
    "common-ui/widgets/charting/D3BarChart",
    "common-ui/widgets/charting/D3BubbleChart",
    "common-ui/widgets/charting/D3HorizontalBarChart",
    "common-ui/widgets/charting/D3LineChart",
    "common-ui/widgets/charting/D3MeasureTrendChart",
    "common-ui/widgets/charting/D3ScatterPlot",
    "common-ui/widgets/charting/D3SparkLineChart",
    "common-ui/widgets/charting/InteractiveLegend",
    "common-ui/widgets/grid/ChartGrid",
    "common-ui/widgets/grid/GridTable",
    "common-ui/widgets/grid/GridButton",
    "common-ui/widgets/form/Form",
    "common-ui/widgets/form/Checkbox",
    "common-ui/widgets/form/TextInput",
    "common-ui/widgets/form/DateTimePicker",
    "common-ui/widgets/form/Switch",
    "common-ui/widgets/Select",
    "common-ui/widgets/Tooltip",
    "common-ui/widgets/utils/colorUtil",
    "common-ui/widgets/utils/reactUtil"
], function(Button, Calendar, Content, DataSet, DomainItem, DomainItemOverview, DomainSummary, FileUpload, Image, InfoTooltip, MeasureItem, SelectionList, Stars, SummaryBar,
            SummaryBarItem, NotificationItem, Notification, OverviewToggleBar, ProgressBar, TitleBar, ToggleBar, SelectionListContainer, ProgrammaticContainer, ToggleBarContainer, ChartListToggleBarContainer, SimpleContainer,
            BubbleLineChart, SparkBarChart, ComparativeBoxPlot, ComparativeBoxPlotLegend, Slider, TimeSlider, Legend, DonutChart, GaugeChart, D3AreaChart, D3BarChart, D3BubbleChart, D3HorizontalBarChart, D3LineChart,
            D3MeasureTrendChart, D3ScatterPlot, D3SparkLineChart, InteractiveLegend, ChartGrid, GridTable, GridButton, Form, Checkbox, TextInput, DateTimePicker, Switch, Select, Tooltip, colorUtil, reactUtil) {

    "use strict";

    return {
        // TODO for react components use this config: "ReactButton" : {react : ReactButton.default},
        "Button" : Button,
        "Calendar" : Calendar,
        "GridButton" : GridButton,
        "Content" : Content,
        "DataSet" : DataSet,
        "DomainItem" : DomainItem,
        "DomainItemOverview" : DomainItemOverview,
        "DomainSummary" : DomainSummary,
        "FileUpload" : FileUpload,
        "Image" : Image,
        "InfoIconTooltip" : InfoTooltip,
        "MeasureItem" : MeasureItem,
        "SelectionList" : Select,
        "SummaryBar" : SummaryBar,
        "Scorecard" : SummaryBar,
        "SummaryBarItem" : SummaryBarItem,
        "NotificationItem" : NotificationItem,
        "Notification" : Notification,
        "OverviewToggleBar" : OverviewToggleBar,
        "Legend" : OverviewToggleBar, // alias for OverviewToggleBar
        "ProgressBar" : ProgressBar,
        "MeasureTrendChart" : D3MeasureTrendChart,
        "SparkLineChart" : D3SparkLineChart,
        "ChartGrid" : ChartGrid,
        "TileGrid" : ChartGrid, // preferred alias for ChartGrid
        "GridTable" : GridTable,
        "LineChart" : D3LineChart,
        "BubbleLineChart" : BubbleLineChart,
        "AreaChart" : D3AreaChart,
        "BarChart" : D3BarChart,
        "PieChart" : DonutChart,
        "Slider" : Slider,
        "TimeSlider" : TimeSlider,
        "ChartLegend" : Legend,
        "DonutChart" : DonutChart,
        "GaugeChart" : GaugeChart,
        "D3BarChart" : D3BarChart,
        "D3BubbleChart" : D3BubbleChart,
        "BubbleChart" : D3BubbleChart,
        "D3HorizontalBarChart" : D3HorizontalBarChart,
        "HorizontalBarChart" : D3HorizontalBarChart,
        "D3LineChart" : D3LineChart,
        "D3MeasureTrendChart" : D3MeasureTrendChart,
        "D3SparkLineChart" : D3SparkLineChart,
        "ScatterPlot" : D3ScatterPlot,
        "D3ScatterPlot" : D3ScatterPlot,
        "InteractiveLegend" : InteractiveLegend,
        "Stars" : Stars,
        "TitleBar" : TitleBar,
        "ToggleBar" : ToggleBar,
        "SelectionListContainer" : SelectionListContainer,
        "ProgrammaticContainer" : ProgrammaticContainer,
        "ToggleBarContainer" : ToggleBarContainer,
        "ChartListToggleBarContainer" : ChartListToggleBarContainer,
        "SimpleContainer" : SimpleContainer,
        "SparkBarChart" : SparkBarChart,
        "ComparativeBoxPlot" : ComparativeBoxPlot,
        "ComparativeBoxPlotLegend" : ComparativeBoxPlotLegend,
        "Form" : Form,
        "Checkbox" : Checkbox,
        "Switch" : Switch,
        "TextInput" : TextInput,
        "DateTimePicker" : DateTimePicker,
        "Select" : Select,
        "Tooltip" : Tooltip,
        "colorUtil" : colorUtil, // this only needs to be imported manually if not using any charting widgets, but using heat map in grid
        "reactUtil" : reactUtil  // this must be included if using react components
    };

});